version: '3'

services:
  #Uncomment if need DB for your purposes
  # Database
  # db:
  #   container_name: ${PROJECT_NAME}.db
  #   image: mysql:5.7
  #   volumes:
  #     - ./db:/var/lib/mysql
  #   restart: always
  #   ports:
  #     - '3306:3306'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${PROJECT_NAME}
  #     MYSQL_USER: ${PROJECT_NAME}
  #     MYSQL_PASSWORD: ${PROJECT_NAME}
  #   networks:
  #     - inner_net

  # Web
  web: 
    env_file:
      - .env
    container_name: ${PROJECT_NAME}.web
    build: 
      context: ./tools/images/web
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes: 
      - ./web:/var/www/html
      - ./shared/errors:/var/www/errors
      - ./shared/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./shared/etc/nginx/sites-enabled/default.conf:/etc/nginx/sites-enabled/default.conf
      - ./shared/etc/php/php.ini:/etc/php7/php.ini
      - ./shared/etc/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./shared/etc/php/www-default.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./shared/var/log/nginx:/var/log/nginx
      - ./shared/var/log/php/php-fpm.log:/usr/local/var/log/php-fpm.log
      
    environment:
      DB_USER: ${PROJECT_NAME}
      DB_PASSWORD: ${PROJECT_NAME}
      RUN_SCRIPTS: 0
      SKIP_COMPOSER: 1
      ENABLE_XDEBUG: ${ENABLE_XDEBUG}
      # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      PHP_VERSION: ${PHP_VERSION}
      PHP_MODULES: ${PHP_MODULES}
      PROGRAMS_TO_INSTALL: ${PROGRAMS_TO_INSTALL}

      #Custom config
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
      PHP_MEM_LIMIT: ${PHP_MEM_LIMIT}
      HIDE_NGINX_HEADERS: ${HIDE_NGINX_HEADERS}
      ERRORS: ${ERRORS}
      NGINX_HOST: ${PROJECT_NAME}.web
      # MYSQL_HOST: ${PROJECT_NAME}.db
    
    networks:
      - inner_net
    #Still not working :(
    deploy:
      resources:
        limits:
          memory: ${MAX_MEMORY_LIMIT}
          cpus: ${MAX_CPU_LIMIT}

networks:
  inner_net:
    